In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("Toddler_Autism - Copy.csv")

In [3]:
df.shape

(1054, 19)

In [4]:
df["Sexn"]= pd.factorize(df.Sex)[0]
df["Ethnicityn"]= pd.factorize(df.Ethnicity)[0]
df["Jaundicen"]= pd.factorize(df.Jaundice)[0]
df["Family_mem_with_ASDn"]= pd.factorize(df.Family_mem_with_ASD)[0]
df["Who_completed_the_testn"]= pd.factorize(df.Who_completed_the_test)[0]

In [5]:
dm=df.drop(['Case_No','Sex', 'Ethnicity','Jaundice','Family_mem_with_ASD','Who_completed_the_test'], axis=1)
dm.head(2)

A1  A2  A3  A4  A5  A6  A7  A8  A9  A10  Age_Mons  Qchat-10-Score  resn  \
0   0   0   0   0   0   0   1   1   0    1        28               3     1   
1   1   1   0   0   0   1   1   0   0    0        36               4     1   

   Sexn  Ethnicityn  Jaundicen  Family_mem_with_ASDn  Who_completed_the_testn  
0     0           0          0                     0                        0  
1     1           1          0                     0                        0

In [36]:
dm.columns
feature_df = dm[['A1','A2','A3','A4','A5','A6','A7','A8','A9','A10','Qchat-10-Score', 'Age_Mons','Ethnicityn','Sexn', 'Jaundicen','Family_mem_with_ASDn','Who_completed_the_testn']]

X = np.asarray(feature_df)
y = np.asarray(dm['resn'])

y[0:15]

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1], dtype=int64)

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [38]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100)

In [39]:
model.fit(X_train, y_train)

RandomForestClassifier()

In [40]:
model.score(X_test, y_test)

0.6161137440758294

In [41]:
y_test[:5]

array([1, 1, 1, 0, 0], dtype=int64)

In [28]:
m=model.predict(X_test)

In [29]:
model.predict_proba(X_test[:10])

array([[0.09      , 0.91      ],
       [0.18766667, 0.81233333],
       [0.43      , 0.57      ],
       [0.36666667, 0.63333333],
       [0.41666667, 0.58333333],
       [0.30833333, 0.69166667],
       [0.96      , 0.04      ],
       [0.14383333, 0.85616667],
       [0.34      , 0.66      ],
       [0.31      , 0.69      ]])

In [30]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, m))

Accuracy: 0.7156398104265402


In [56]:
from sklearn.model_selection import cross_val_score
cross_val_score(RandomForestClassifier(n_estimators=100),X_train, y_train, cv=5)

array([0.94444444, 0.94444444, 0.94444444, 0.94444444, 0.88235294])

In [57]:
dm = pd.read_csv('Batsman_Current - Copy.csv')

In [58]:
dm['rating'] = dm['Runs'] / dm['Inns'] + dm['Runs'] / dm['BF'] + dm['hundred'] + dm['fifty'] / dm['Inns'] + dm['four']*4 / dm['Inns'] + dm['six']*6 / dm['Inns']+ df['zero'] / df['Inns']

In [59]:
p=dm.drop(['Player','Span','rating'],axis='columns')

In [60]:
dm.head(10)

Player       Span  Mat  Inns  NO  Runs   HS    Ave    BF  \
0        Afif Hossain  2020-2020    1     1   0     7    7   7.00     4   
1     Al-Amin Hossain  2014-2020   15     7   5     4    2   2.00    20   
2        Anamul Haque  2012-2019   38    52   0  1052  120  30.05  1488   
3           Liton Das  2015-2020   36    36   3  1079  176  32.69  1133   
4         Mahmudullah  2007-2020  188   163  42  4070  128  33.63  5311   
5    Mashrafe Mortaza  2001-2020  218   156  28  1773   51  13.85  2021   
6  Mehidy Hasan Miraz  2017-2020   41    26   4   393   51  17.86   508   
7     Mohammad Mithun  2014-2020   27    23   3   575   63  28.75   718   
8  Mohammad Saifuddin  2017-2020   22    13   4   290   51  32.22   337   
9    Mosaddek Hossain  2016-2019   35    30  10   549   52  27.45   633   

       SR  hundred  fifty  zero  four  six     rating  
0  175.00        0      0     0     1    0  12.873711  
1   20.00        0      0     2     0    0   0.771429  
2   70.69        3      3     6   103   19  34.110835  
3   95.23        3      3     4   113   22  50.230117  
4   76.63        3     21     8   317   57  38.835912  
5   87.72        0      1    15   150   62  18.479853  
6   77.36        0      1     0    39    4  22.918727  
7   80.08        0      5     1    49   14  38.267898  
8   86.05        0      2     1    24    6  33.761633  
9   86.72        0      2     1    53   11  28.707528

In [61]:
model.predict(p[:10])

array(['0', '0', '1', '1', '1', '0', '1', '1', '1', '1'], dtype=object)

In [62]:
pre = dm['rating'].apply(lambda x: '1' if x >= 20 else '0')

In [63]:
pre.head(10)

0    0
1    0
2    1
3    1
4    1
5    0
6    1
7    1
8    1
9    1
Name: rating, dtype: object

In [64]:
s=dm.sort_values(by='rating', ascending=False)

In [65]:
s.head(6)

Player       Span  Mat  Inns  NO  Runs   HS    Ave    BF     SR  \
19      Tamim Iqbal  2007-2020  207   205   9  7202  158  36.74  9153  78.68   
16  Shakib Al Hasan  2006-2019  206   194  27  6323  134  37.86  7641  82.75   
17    Soumya Sarkar  2014-2019   55    54   3  1728  127  33.88  1753  98.57   
10  Mushfiqur Rahim  2006-2020  218   204  34  6174  144  36.31  7794  79.21   
3         Liton Das  2015-2020   36    36   3  1079  176  32.69  1133  95.23   
4       Mahmudullah  2007-2020  188   163  42  4070  128  33.63  5311  76.63   

    hundred  fifty  zero  four  six     rating  
19       13     47    18   783   91  67.339285  
16        9     47    10   574   42  55.887491  
17        2     11     5   200   42  54.828819  
10        7     38    10   492   82  50.430157  
3         3      3     4   113   22  50.230117  
4         3     21     8   317   57  38.835912

In [66]:
k=s.Player

In [67]:
k.head(6)

19        Tamim Iqbal
16    Shakib Al Hasan
17      Soumya Sarkar
10    Mushfiqur Rahim
3           Liton Das
4         Mahmudullah
Name: Player, dtype: object